name: Package Release
on:
  push:
    branches:
      - main # Later, we would like to change this to "release".
  pull_request:
    branches:
      - main # Later, we would like to change this to "release".

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.13" ]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        # language=bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
      - name: Build
        # language=bash
        run: |
          uv build
      - name: Store the package
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  ############################
  # Publish to the test repo #
  ############################
  publish-to-testpypi:
    name: Publish to the test server
    needs:
      - build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/deferrable-py

    permissions:
      id-token: ${{ pypi }}

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution 📦 to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      
